create type name as (fname varchar(100),lname varchar(100));
create type addr as (street varchar(100),city varchar(100),postal_code integer);
create table inventor(id serial primary key,name name,address addr,dob date,age integer,salary integer,Recieved_Awards varchar(500));
insert into inventor(name,address,dob,age,salary,Recieved_Awards)values(('Sarang','Dileep')::name,('Meloor','Thalassery',123)::addr,'2001-07-27',12,12343,'Nobel prize');
create table category(category_name varchar(100),category_id serial primary key);
insert into category values('crypto');
create table invention(in_id serial primary key,year_of_invention integer,Budget integer,id integer,story varchar(10000),year_of_win integer,category_id integer,constraint id foreign key(id) References inventor(id),constraint category_id foreign key(category_id) References category(category_id));
insert into invention(year_of_invention,Budget,id,story,year_of_win,category_id) values(2010,100000,2,'It was very great',2011,1);
create table nominee(nid serial primary key,rating numeric(2,1),in_id integer,category_id integer,constraint in_id foreign key(in_id) references invention(in_id),constraint category_id foreign key(category_id) references category(category_id));
insert into nominee(rating,in_id,category_id) values (9.6,2,1);
create table winner(n_id integer,constraint n_id foreign key(n_id) references nominee(nid));
insert into winner values(1);
create table award( award_id serial primary key,award_name varchar(100), organisation varchar(100),country varchar(50),id integer,category_id integer,constraint id foreign key(id) references inventor(id),constraint category_id foreign key(category_id) references category(category_id));
insert into award(award_name,organisation,country,id,category_id) values ('Nobel prize','Karolinska Institute','Norway',2,1);
